directories:
  persist_vector_directory: data/vector_db
  data_pdf_education_directory: data/data_education.pdf
  data_csv_education_directory: data/data_education.csv
  persist_chunk_directory: data/data_chunked_education.pkl

llm_config:
  rag_model: llama3-70b-8192
  summarize_model: llama3-8b-8192
  temperature: 0.0
  max_token: 850

retriever_config:
  similarity_score: 0.6
  embedding_model: BAAI/bge-small-en-v1.5
  vector_embed_size: 384
  top_k: 3

chunk_config:
  chunk_size: 1024
  chunk_overlap: 300
  max_attempts: 3
  delimiter: "####"
  model_name: 'gpt2'